# Generated by Django 3.1.6 on 2021-02-11 23:30

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('first_name', models.CharField(db_column='first_name', max_length=250)),
                ('last_name', models.CharField(blank=True, db_column='last_name', max_length=250, null=True)),
                ('phone', models.CharField(db_column='phone', max_length=14)),
                ('email', models.EmailField(blank=True, max_length=150, null=True)),
                ('update_at', models.DateTimeField(auto_now=True, db_column='update_at')),
            ],
            options={
                'db_table': 'profile',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('first_name', models.CharField(blank=True, max_length=150, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='last name')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='email address')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('username', models.CharField(db_index=True, max_length=150, unique=True)),
                ('is_active', models.BooleanField(default=True)),
                ('role', models.CharField(choices=[('ROLE_ADMIN', 'Administrator'), ('ROLE_SUPERVISOR', 'Supervisor'), ('ROLE_SUPER_ADMIN', 'Super Admin'), ('ROLE_PARTNER', 'Partner'), ('ROLE_USER', 'Advisor')], max_length=30)),
                ('created_at', models.DateTimeField(db_column='created_at', default=django.utils.timezone.now)),
                ('update_at', models.DateTimeField(auto_now=True, db_column='update_at')),
                ('deleted', models.BooleanField(blank=True, default=False, null=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.Group', verbose_name='groups')),
                ('profile', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='users.profile')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.Permission', verbose_name='user permissions')),
            ],
            options={
                'db_table': 'user',
                'ordering': ['-id'],
            },
        ),
        migrations.CreateModel(
            name='BlackListedToken',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('token', models.TextField()),
                ('jti', models.CharField(max_length=255, null=True)),
                ('type', models.CharField(choices=[('TOKEN', 'Pending'), ('REFRESH_TOKEN', 'Validated')], default='TOKEN', max_length=14)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('expired_at', models.DateTimeField(null=True)),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='token_user', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'blacklisted_token',
                'ordering': ['id'],
                'unique_together': {('token', 'user')},
            },
        ),
    ]
