# Generated by Django 3.1.6 on 2021-02-13 08:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('ROLE_ADMIN', 'Administrator'), ('ROLE_SUPERVISOR', 'Supervisor'), ('ROLE_SUPER_ADMIN', 'Super Admin'), ('ROLE_USER', 'User')], max_length=30),
        ),
    ]
