# Generated by Django 3.1.6 on 2021-03-31 18:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_auto_20210219_1356'),
    ]

    operations = [
        migrations.RenameField(
            model_name='elector',
            old_name='birth_date',
            new_name='birthDate',
        ),
        migrations.RenameField(
            model_name='elector',
            old_name='birth_place',
            new_name='birthPlace',
        ),
        migrations.AddField(
            model_name='elector',
            name='gender',
            field=models.CharField(blank=True, max_length=8),
        ),
        migrations.AddField(
            model_name='elector',
            name='localisation',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='elector',
            name='phone',
            field=models.CharField(db_column='phone', max_length=14, null=True),
        ),
        migrations.AlterField(
            model_name='elector',
            name='birthDate',
            field=models.DateField(db_column='birth_date'),
        ),
        migrations.AlterField(
            model_name='elector',
            name='birthPlace',
            field=models.CharField(db_column='birth_place', max_length=255),
        ),
    ]
